services:
  api:
    build:
      context: .
      dockerfile: docker/images/app/Dockerfile
    env_file:
      - .env
    ports:
      - '3150:3150'
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PGHOST=db
      - PGUSER=postgres
      - DATABASE_URL=${DATABASE_URL}

  db:
    image: postgres:12.1
    env_file:
      - .env
    volumes:
      - ./bin/db-setup:/bin/db-setup

    ports:
      - '5400:5432'
